apiVersion: v1
kind: Service
metadata:
  name: dataservice
  labels:
    app: data
spec:
  type: ClusterIP
  ports:
  - name: http-dataservice
    port: 9090
    targetPort: 9090
  - name: http-listener
    port: 8300
    targetPort: 8300
  - name: http-admin
    port: 8301
    targetPort: 8301
  selector:
    app: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataservice
  labels:
    app: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: dataservice
        image: morvencao/dataservice:v2.0
        ports:
        - containerPort: 9090
      - name: sidecar-envoy
        image: envoyproxy/envoy:latest
        ports:
        - containerPort: 8300
        - containerPort: 8301
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/sidecar-envoy.yaml", "--service-cluster", "dataservice", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy-config/
      volumes:
      - name: envoy-config
        configMap:
          name: data-sidecar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-sidecar
  labels:
    app: data
data:
  sidecar-envoy.yaml: |-
    # frontend envoy proxy configuration
    admin:
      access_log_path: "/var/log/acces.log"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8301
    node:
      cluster: dataservice-envoy-cluster
      id: dataservice-envoy
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 1s
        type: strict_dns
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: envoy-xds
            port_value: 15010
      - name: jaeger
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: zipkin
            port_value: 9411
    dynamic_resources:
      cds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
          - envoy_grpc:
              cluster_name: xds_cluster
      lds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
          - envoy_grpc:
              cluster_name: xds_cluster
    tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: jaeger
          collector_endpoint: "/api/v1/spans"
          shared_span_context: false
